[project]
name = "splaud"
version = "0.1.0"
description = "Cross-platform audio splitting made simple"
readme = "README.md"
authors = [
    { name = "Kir Koov", email = "k.koovshinov@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
splaud = "splaud:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
